### ISSUE TITLE
Initial Login/Sign-Up Screen

### ISSUE THREAD

**Issue by CordellRadke** [CordellRadke/capstone#10]
The user should have the ability to create an account or sign in to an account that was already created.  Use of AsyncStorage.

**Comment by brandonbrown** [comment]
> Use of AsyncStorage.

What is the use of AsyncStorage here?

**Comment by brandonbrown** [comment]
@CordellRadke the way you stated it in your initial issue was too general purpose. Maybe you meant "initialize" use of asyncstorage? Using async to keep data local and then sync out with your server in a more controlled way is the best practice for mobile devices.
