### ISSUE TITLE
(Garage) CRUD Vehicles 

### ISSUE THREAD

**Issue by CordellRadke** [CordellRadke/capstone#11]
Vehicles should be stored in a database (Express & MongoDB). User can either add, edit, or delete a Vehicle from the garage. Editing will bring user back to registration screen to change the Vehicle specs.

**Comment by brandonbrown** [comment]
> Editing will bring user back to registration screen to change the Vehicle specs.

Did you mean to include registration as the target screen? Wording it this way makes it seem the user only has the ability to store a single car in the application.
