### ISSUE TITLE
CARHUB

### ISSUE THREAD

**Issue by CordellRadke** [CordellRadke/capstone#12]
User will have three tab options at bottom of the screen. History/Costs/Videos. Find a shop feature may come later in development. In the Carhub users will see their alerts such as when they need their next oil change. This will be inputted by the user, at start, to figure out the last time they got an oil change and how many miles to the next oil change. Carhub will also display if their vehicle is safe to drive depending on the recent reports the user has inputted.

**Comment by brandonbrown** [comment]
> Carhub will also display if their vehicle is safe to drive depending on the recent reports the user has inputted.

I do not recommend including this as a feature until you have a really, really good legal team. You may want to consider "Vehicle Efficiency" or "Vehicle Capabilities" as the title for this feature if you would like to continue with it as a requirement.

**Comment by CordellRadke** [comment]
@brandonbrown By recent reports, I mean things like when was the last time the user inputted a oil and mile change if that makes a difference.  Not necessarily "accident" reports. I'll definitely take Vehicle Efficiency as a consideration for sure.
