### ISSUE TITLE
Requested open critique

### ISSUE THREAD

**Issue by reactivepixel** [CordellRadke/capstone#4]
Below are a number of comments and questions. Don't feel like you need to respond to each one here, but understand that these question will be asked of you in the future and you will need to have well thought through answers at that point. Some of the questions I am proposing are mostly to get you to think through various parts of your design and consider the choices you have made.

Also, keep in mind that I am asking hard questions and providing critical feedback to challenge you to build the best application you can.

## General Comments
* Why does this application need to be react native?
* The title "CSR Car Service Repair" might mislead users into thinking your app offers repairs.
* Drop shadowed buttons and icons tend to have a  dated look and feel.
* When choosing a navigational scheme try and stick to similar button shapes, colors, placement.
* Overall It is unclear to me what problem your application is solving as there seem to be some major pieces of functionality missing from the design.

## Splash Screen
* Once the video finishes is the expected interaction to click "Skip" to proceed forward?
* How common is a video tutorial splash screen for your intended audience?

## Car Registration Screen
* Where does the back button return to?
* "What's your license plate?" feels out of place when looking at the information hierarchy of the page. It is indented, a lighter color, and a smaller font size than the text inputs.
* This page feels like its purpose is not accurately communicated to the user. 
* This is a rather daunting form, though it is a standard setup for car info entries. Consider visiting a local car parts store to watch how they (an experienced user familiar with similar data input) interact with their interface, and the design choices made by that interface's designer.
* Do you need all of this information? Do you need more? I note that "Model" is specified but Make or Manufacturer is not, when it is a common input field for this content.
* Nickname of Vehicle feels a little forced. Is there a better way to capture this information?
* Folder icon could confuse some users.
* Styling on the Continue button looks too similar to styling on the "car registration" header. Users may perceive both to be buttons.
* New document icon on the right of the header feels out of place, under what circumstances do you see the user selecting that option. Additionally, this interaction is styled differently from other interactions and may go unnoticed.
* Every other screen seems to have access to the hamburger stack nav except this screen, why?

## Garage Screen
* Very small font choice for the car info.
* 3 dots icon feels undersized compared to the thumbnail picture size.
* Add vehicle icon/button is too difference from other expected interaction elements. Consider building a stronger harmony between all of your interaction elements.
* The user's expected behavior on this page is ambiguous. What is the intent, clearly communicate that your users.

## Carhub Screen
* This screen is wildly different from your others and I, as a new user, am overwhelmed. You have gone through efforts to teach me how to use your interface and then you have just changed the main styles of most all elements. My vehicle, old betsy is displayed in a manner unlike the previous screen it was displayed on, what is the reason for this?
* Low fuel: How do you plan to accurately track this?
*These alerts feel tacked on rather than well thought through and display meaningful information in a meaningful manner.
* Footer nav is new on this screen but not on others. Additionally, it's of yet another interaction style.

## Cost/Estimates Screen
* I think I'm lost at this point, based upon your description on your readme I understood this as an application to keep track of the vital records of your vehicle over time, like a service log. But this screen seems to dramatically deviated from expected functionality. I have no idea what is/should be displayed here. Likewise, users, if presented with this screen may be come confused with what exactly is the intention of this screen.
* Find a shop icon is different from other footer nav styles.
* Search part info - No idea what selecting this should return. 
* Where is this info driving this graph coming from?

## Medals Screen
* Yes, people love rewards, but throwing this feature in feels not thought through. You want to offer value in the features that you include. I don't see a value defined in these medals to your audience. Ideally you build reward systems around behaviors in your users you want to encourage. "You've used the app X days in a row, good job, here's a confirmation that you are doing the things we like!" or "You've used one of the maintenance facilities we are affiliated with, great job, here's 10% off this time... do it 5 more times for another 10% then!"
* Just showing locks and not how each medal can be achieved prevents your users from working toward preforming the actions you desire.

**Comment by brandonbrown** [comment]
Added further feedback: https://projects.invisionapp.com/freehand/document/jHkV9SYhs
